# Generated by Django 5.0.6 on 2024-07-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_posttbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttbl',
            name='likes',
        ),
    ]
