# Generated by Django 5.0.6 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_posttbl_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttbl',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
