# Generated by Django 5.0.6 on 2024-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_posttbl_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttbl',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
