# Generated by Django 5.0.6 on 2024-07-18 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_posttbl_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttbl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttbl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
