# Generated by Django 5.0.6 on 2024-07-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_posttbl_created_at_posttbl_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttbl',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='posttbl',
            name='updated_at',
        ),
    ]
