# Generated by Django 5.0.6 on 2024-07-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_posttbl_created_at_remove_posttbl_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='commenttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentcontent', models.CharField(max_length=500)),
                ('postidF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.posttbl')),
            ],
        ),
    ]
