# Generated by Django 5.0.6 on 2024-07-18 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_commenttbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttbl',
            name='postidF',
        ),
        migrations.AddField(
            model_name='commenttbl',
            name='postidPF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.posttbl'),
        ),
        migrations.AddField(
            model_name='commenttbl',
            name='useridUF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usertbl'),
        ),
    ]
