# Generated by Django 5.0.6 on 2024-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_liketbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketbl',
            name='likeaction',
            field=models.BooleanField(default=False),
        ),
    ]
