# Generated by Django 5.0.6 on 2024-07-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_liketbl_likeaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liketbl',
        ),
    ]
