# Generated by Django 5.0.6 on 2024-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_delete_liketbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttbl',
            name='likeddetails',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='userapp.usertbl'),
        ),
    ]
