# Generated by Django 5.0.6 on 2024-07-21 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_posttbl_likeddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttbl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
