# Generated by Django 5.0.6 on 2024-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_posttbl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttbl',
            name='created_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
